#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Trackback
version:      1.01
version_from: lib/Net/Trackback.pm
installdirs:  site
requires:
    LWP:                           5.8
    Class::ErrorHandler:           0.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
