#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Trackback
version:      1
version_from: lib/Net/Trackback.pm
installdirs:  site
requires:
    LWP:                           Class::ErrorHandler

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
